/**
 * Deterministic Explainable-AI builders for the food-log pipeline.
 *
 * NutriSLM's XAI contract: the AI (LLM vision/text model) only PERCEIVES — it
 * identifies foods and estimates quantities. Every nutrition NUMBER comes from
 * the verified food database via a deterministic calculator. Explanations here
 * are therefore composed from real pipeline data (match status, confidence,
 * conversions, data sources) — never generated or paraphrased by an LLM.
 *
 * Consumers: confirm-food + log-meal routes (server), XAI UI components (client).
 */

export interface LineExplanation {
  /** One-line plain-language answer to "why this number?". */
  summary: string;
  /** Ordered reasoning bullets (portion math → conversion → provenance → confidence). */
  factors: string[];
  /** Provenance tags rendered as badges. */
  dataQuality: "verified" | "unmatched";
}

export interface Contribution {
  name: string;
  kcal: number;
  /** Share of the meal's calories, 0..100 rounded to an integer. */
  pct: number;
}

export interface TotalsExplanation {
  /** One-liner, e.g. "4 items from the verified database — paneer (48%) leads the calories." */
  summary: string;
  /** Per-food calorie contributions, sorted descending. */
  contributors: Contribution[];
  /** Method bullets that apply to the meal as a whole. */
  factors: string[];
}

export interface LineExplanationInput {
  displayName: string;
  originalName: string | null;
  quantity: number;
  unit: string;
  matched: boolean;
  /** e.g. "IFCT2017" */
  source: string | null;
  /** Reference amount the DB values are expressed in, e.g. "100 g" | "1 piece". */
  reference: string | null;
  /** Human note from convertQuantity when the unit needed conversion. */
  conversionNote: string | null;
  /** True when the request unit differs from the food's reference unit. */
  converted: boolean;
  /** AI recognition confidence 0..1 (null = user-entered / user-resolved). */
  confidence: number | null;
  /** user | estimated | unknown */
  quantitySource: string;
  /** True when the user changed quantity/unit/food after the AI draft. */
  userEdited: boolean;
  /** Approximate reference amounts consumed, when known. */
  quantityInRefs?: number | null;
}

/** Build the per-line "why this number?" explanation. Purely deterministic. */
export function buildLineExplanation(input: LineExplanationInput): LineExplanation {
  const name = input.displayName || input.originalName || "This item";

  if (!input.matched) {
    return {
      summary: `${name} is not in the food database yet, so it contributes 0 nutrition — pick a close match from the food search for accurate totals.`,
      factors: [
        "No database entry → no verified nutrition values available.",
        "NutriSLM never invents numbers: unmapped foods log with 0 kcal instead of a guess.",
        "Search the food database to swap in the closest verified alternative.",
      ],
      dataQuality: "unmatched",
    };
  }

  const factors: string[] = [];

  // 1. Portion math — the scaled reference.
  if (input.converted) {
    factors.push(
      input.conversionNote ??
        `${input.quantity} ${input.unit} was converted to the food's reference amount using standard portion weights.`,
    );
  } else if (input.quantityInRefs != null) {
    const refs = round2(input.quantityInRefs);
    factors.push(
      `Portion math: ${formatQty(input.quantity)} ${input.unit} = ${refs} × reference (${input.reference ?? "reference amount"}), so nutrition scales linearly.`,
    );
  } else {
    factors.push(`Portion math: nutrition scales linearly from the ${input.reference ?? "reference"} amount.`);
  }

  // 2. Provenance — where the numbers come from.
  factors.push(
    `Nutrition values are verified database figures (${input.source ?? "food database"}) per ${input.reference ?? "reference amount"} — not generated by AI.`,
  );

  // 3. Quantity provenance — who decided the amount.
  if (input.userEdited) {
    factors.push("You adjusted the quantity/unit, so the final amount reflects your input.");
  } else if (input.quantitySource === "estimated") {
    factors.push(
      input.confidence != null
        ? `The amount was estimated by AI from your description (${Math.round(input.confidence * 100)}% overall confidence) — adjust it if the portion differs.`
        : "The amount was estimated by AI from your description — adjust it if the portion differs.",
    );
  } else if (input.quantitySource === "unknown") {
    factors.push("The AI could not tell the portion size — please verify the quantity before logging.");
  } else {
    factors.push("The amount is exactly what you specified.");
  }

  // 4. Recognition confidence — how sure perception was about WHAT the food is.
  if (input.confidence != null && input.confidence < 1 && !input.userEdited) {
    factors.push(
      input.confidence >= 0.8
        ? `Food recognition was confident (${Math.round(input.confidence * 100)}%).`
        : `Food recognition confidence was lower (${Math.round(input.confidence * 100)}%) — check the item is what you ate.`,
    );
  }

  const qty =
    input.quantitySource === "estimated"
      ? "AI-estimated portion"
      : input.quantitySource === "unknown"
        ? "unclear portion"
        : "your portion";

  const summary = input.converted
    ? `${formatQty(input.quantity)} ${input.unit} of ${name} ≈ scaled from the verified ${input.source ?? "database"} reference — conversion applied, ${qty}.`
    : `${formatQty(input.quantity)} ${input.unit} of ${name} = linear scale of the verified ${input.source ?? "database"} value (${input.reference ?? "reference"}), ${qty}.`;

  return { summary, factors, dataQuality: "verified" };
}

export interface TotalsExplanationInput {
  lines: { displayName: string; kcal: number; matched: boolean; source: string | null }[];
  totalsKcal: number;
  incomplete: boolean;
  anyConverted: boolean;
  anyEstimated: boolean;
}

/** Build the meal-level "how were these totals calculated?" explanation. */
export function buildTotalsExplanation(input: TotalsExplanationInput): TotalsExplanation {
  const matched = input.lines.filter((l) => l.matched);
  const kcalTotal = input.totalsKcal > 0 ? input.totalsKcal : 0;

  const contributors: Contribution[] = input.lines
    .map((l) => ({
      name: l.displayName,
      kcal: round2(l.kcal),
      pct: kcalTotal > 0 && l.matched ? Math.round((l.kcal / kcalTotal) * 100) : 0,
    }))
    .sort((a, b) => b.kcal - a.kcal);

  const factors: string[] = [
    `Every value is re-calculated server-side from the verified food database — the frontend never supplies nutrition numbers.`,
    matched.length > 0
      ? `${matched.length} item${matched.length === 1 ? "" : "s"} matched to verified entries (${[...new Set(matched.map((l) => l.source).filter(Boolean))].join(", ") || "food database"}).`
      : "No items matched the database — totals are 0.",
  ];
  if (input.anyConverted) {
    factors.push("Household units (cup, katori, chapati…) were converted to reference weights using standard portion sizes.");
  }
  if (input.anyEstimated) {
    factors.push("At least one portion was AI-estimated — the review step flagged it so you can confirm or adjust.");
  }
  if (input.incomplete) {
    factors.push("Some items were unmatched; they add 0 to the totals (honest zeros instead of guesses).");
  }

  const lead = contributors[0];
  const summary =
    matched.length === 0
      ? "No verified items — totals are 0 until foods are matched."
      : `${matched.length} verified item${matched.length === 1 ? "" : "s"}${
          lead && lead.pct > 0 ? ` — ${lead.name} contributes ${lead.pct}% of the calories` : ""
        }${input.anyEstimated ? ", one or more portions AI-estimated" : ""}.`;

  return { summary, contributors, factors };
}

function formatQty(q: number): string {
  return Number.isInteger(q) ? String(q) : String(round2(q));
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}
